# &0 = Black  |  &1 = DarkGray
# &2 = GRAY   |  &w = White
# &r = Red    |  &R = DarkRed
# &y = YELLOW |  &Y = Gold
# &g = Green  |  &G = DarkGreen
# &c = Cyan   |  &C = DarkCyan
# &b = Blue   |  &B = DarkBlue
# &p = Purple |  &P = DarkPurple
# Extra Formatting:
# %bold | %italic | %underline | %strike | %reset
# &# = Pagination digit
rules:
  default: |
    &r Server Rules&2 [&Y3&2 warnings = &RAuto-Ban&2]
    &2 - - - - - - - - - - - - - - - - - - - -
    &2&#. &rNo Hacked Clients / Xray
    &2&#. &rBe courteous and respect others.
    &2&#. &rDon't steal from chests / furances / dispensers.
    &2&#. &rDon't randomly destroy or spam blocks.
    &2&#. &rDon't destroy or interfere with a build which is not yours.
    &2&#. &rDon't beg for rank or items.
    &2&#. &rDo not kill players, pvp is allowed only when agreed to, or in your own house.
    &2&#. &rNo tunneling with worldedit.
    &2&#. &YIf it's not creative it's destructive, and if it's destructive it's not welcome.
  PVP: |
    &r Server Rules&2 [&Y3&2 warnings = &RAuto-Ban&2]
    &2 - - - - - - - - - - - - - - - - - - - -
    &2&#. &bold&rNo Hacked Clients / Xray&reset
    &2&#. &rBe courteous and respect others.
    &2&#. &rDon't randomly destroy or spam blocks.
    &2&#. &rDon't beg for rank or items.
    &2&#. &rNo tunneling with worldedit.
motd:
- '&2Hello, &Y%player&2. Welcome to &YThe Orphanage.'
- '&2[&Chttp://Orphanage.DynDNS.info&2]'
- '&r*** Please read the rules by typing &g/rules &r***'

whereintheworld:
    world: "&Y%player&2 currently in &c%world&2"
    noplayer: "&Y%player&2 is offline or not exists!"